spring:
  kafka:
    bootstrap-servers: localhost:9092   # or kafka:9092 if your app runs in Docker
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: order-service-logger
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"   # or restrict to your package
    listener:
      ack-mode: record

app:
  outbox:
    refund-topic: refunds.requested
    refund-dlt-topic: refunds.requested.DLT

logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.transaction.interceptor: debug
    com.zomato.vehicle: info
